/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class PerhitunganDiskonFrame extends javax.swing.JFrame {

    /**
     * Creates new form PerhitunganDiskonFrame
     */
    public PerhitunganDiskonFrame() {
        initComponents();
            setLocationRelativeTo(null); // biar tampil di tengah

    try {
        // Ambil gambar dari src
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"));
        java.awt.Image img = icon.getImage().getScaledInstance(
                jPanel1.getWidth(),
                jPanel1.getHeight(),
                java.awt.Image.SCALE_SMOOTH
        );

        javax.swing.JLabel bg = new javax.swing.JLabel(new javax.swing.ImageIcon(img));
        bg.setBounds(0, 0, jPanel1.getWidth(), jPanel1.getHeight());

        // Tambahkan background ke panel
        jPanel1.add(bg);
        jPanel1.setComponentZOrder(bg, jPanel1.getComponentCount() - 1);
    } catch (Exception e) {
        System.out.println("Gagal memuat background: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Harga = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextHasil = new javax.swing.JTextField();
        Diskon = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Diskon1 = new javax.swing.JLabel();
        TextHarga = new javax.swing.JTextField();
        BtnHitung = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        Diskon2 = new javax.swing.JLabel();
        TextRedeem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextRiwayat = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Harga.setFont(new java.awt.Font("Milky Nice", 0, 18)); // NOI18N
        Harga.setText("harga :");

        jLabel3.setFont(new java.awt.Font("ND LOGOS", 0, 18)); // NOI18N
        jLabel3.setText("kuni store");

        TextHasil.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        TextHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHasilActionPerformed(evt);
            }
        });

        Diskon.setFont(new java.awt.Font("Milky Nice", 0, 18)); // NOI18N
        Diskon.setText("Diskon :");

        jComboBox1.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "15%", "20%", "35%" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Diskon1.setFont(new java.awt.Font("Milky Nice", 0, 18)); // NOI18N
        Diskon1.setText("Anda hemat :");

        TextHarga.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        TextHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHargaActionPerformed(evt);
            }
        });

        BtnHitung.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        BtnHitung.setText("Hitung");
        BtnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitungActionPerformed(evt);
            }
        });

        jSlider1.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        Diskon2.setFont(new java.awt.Font("Milky Nice", 0, 18)); // NOI18N
        Diskon2.setText("kode Redeem :");

        TextRedeem.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        TextRedeem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRedeemActionPerformed(evt);
            }
        });

        TextRiwayat.setColumns(20);
        TextRiwayat.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        TextRiwayat.setRows(5);
        jScrollPane1.setViewportView(TextRiwayat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Harga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnHitung)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Diskon2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextRedeem, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Diskon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 162, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Diskon1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TextHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Harga)
                    .addComponent(TextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diskon)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diskon2)
                    .addComponent(TextRedeem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(BtnHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Diskon1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Evogria", 0, 18)); // NOI18N
        jLabel2.setText("aplikasi perhitungan diskon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHasilActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TextHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHargaActionPerformed

    private void BtnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitungActionPerformed
try {
            double harga = Double.parseDouble(TextHarga.getText().trim());
            double diskon = 0.0;

            // Ambil pilihan diskon dari combo box
            String selectedDiskon = (String) jComboBox1.getSelectedItem();
            if (selectedDiskon != null) {
                switch (selectedDiskon) {
                    case "10%": diskon = 10; break;
                    case "15%": diskon = 15; break;
                    case "20%": diskon = 20; break;
                    case "35%": diskon = 35; break;
                }
            }

            int sliderValue = jSlider1.getValue();
            double diskonAkhir = (diskon + sliderValue) / 2.0;

            String kode = TextRedeem.getText().trim().toUpperCase();
            double tambahan = 0.0;
            if ("KUN2025".equals(kode)) tambahan = 25;
            else if ("NINO21".equals(kode)) tambahan = 21;

            double totalDiskon = diskonAkhir + tambahan;
            if (totalDiskon > 100) totalDiskon = 100;

            double potongan = harga * totalDiskon / 100.0;
            double hasil = harga - potongan;

            TextHasil.setText(String.format("Rp %.2f", hasil));

            TextRiwayat.append(String.format(
                "Harga: Rp %.2f | Diskon: %.1f%%%s | Hemat: Rp %.2f | Total: Rp %.2f%n",
                harga, diskonAkhir,
                (tambahan > 0 ? " + Redeem " + tambahan + "%" : ""),
                potongan, hasil));

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Masukkan angka yang valid pada kolom harga!",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnHitungActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        int value = jSlider1.getValue();
        if (value <= 12) jComboBox1.setSelectedItem("10%");
        else if (value <= 17) jComboBox1.setSelectedItem("15%");
        else if (value <= 27) jComboBox1.setSelectedItem("20%");
        else jComboBox1.setSelectedItem("35%");
    }//GEN-LAST:event_jSlider1StateChanged

    private void TextRedeemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRedeemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRedeemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerhitunganDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerhitunganDiskonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHitung;
    private javax.swing.JLabel Diskon;
    private javax.swing.JLabel Diskon1;
    private javax.swing.JLabel Diskon2;
    private javax.swing.JLabel Harga;
    private javax.swing.JTextField TextHarga;
    private javax.swing.JTextField TextHasil;
    private javax.swing.JTextField TextRedeem;
    private javax.swing.JTextArea TextRiwayat;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
